-- Site content settings moved to types/site-settings.ts
-- Edit that file and redeploy instead of running this script.
--
-- Legacy reference (optional — no longer used by the public site):
-- INSERT INTO public.site_settings ...
